export const user = {
  login: "matheuspinh",
  id: 79063983,
  node_id: "MDQ6VXNlcjc5MDYzOTgz",
  avatar_url: "https://avatars.githubusercontent.com/u/79063983?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/matheuspinh",
  html_url: "https://github.com/matheuspinh",
  followers_url: "https://api.github.com/users/matheuspinh/followers",
  following_url:
    "https://api.github.com/users/matheuspinh/following{/other_user}",
  gists_url: "https://api.github.com/users/matheuspinh/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/matheuspinh/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/matheuspinh/subscriptions",
  organizations_url: "https://api.github.com/users/matheuspinh/orgs",
  repos_url: "https://api.github.com/users/matheuspinh/repos",
  events_url: "https://api.github.com/users/matheuspinh/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/matheuspinh/received_events",
  type: "User",
  site_admin: false,
  name: "Matheus Pinheiro",
  company: null,
  blog: "https://matheuspinh.vercel.app/",
  location: "Rio de janeiro",
  email: null,
  hireable: null,
  bio: "Desenvolvedor Full Stack | Back-end | Front-end | JavaScript | Node.js | React | HTML | CSS | SQL",
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 14,
  following: 12,
  created_at: "2021-02-14T22:39:24Z",
  updated_at: "2023-08-08T12:28:21Z",
};
